<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;
    protected $guarded = [];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::deleting(function ($model){
            CategoryProduct::query()
                ->where('category_id' , $model->id)
                ->delete();
        });
    }
}
